// Generated by gencpp from file template_ros/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TEMPLATE_ROS_MESSAGE_ADDTWOINTS_H
#define TEMPLATE_ROS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <template_ros/AddTwoIntsRequest.h>
#include <template_ros/AddTwoIntsResponse.h>


namespace template_ros
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace template_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::template_ros::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::template_ros::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::template_ros::AddTwoInts > {
  static const char* value()
  {
    return "template_ros/AddTwoInts";
  }

  static const char* value(const ::template_ros::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::template_ros::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::template_ros::AddTwoInts > 
template<>
struct MD5Sum< ::template_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::template_ros::AddTwoInts >::value();
  }
  static const char* value(const ::template_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::template_ros::AddTwoIntsRequest> should match 
// service_traits::DataType< ::template_ros::AddTwoInts > 
template<>
struct DataType< ::template_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::template_ros::AddTwoInts >::value();
  }
  static const char* value(const ::template_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::template_ros::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::template_ros::AddTwoInts > 
template<>
struct MD5Sum< ::template_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::template_ros::AddTwoInts >::value();
  }
  static const char* value(const ::template_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::template_ros::AddTwoIntsResponse> should match 
// service_traits::DataType< ::template_ros::AddTwoInts > 
template<>
struct DataType< ::template_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::template_ros::AddTwoInts >::value();
  }
  static const char* value(const ::template_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEMPLATE_ROS_MESSAGE_ADDTWOINTS_H
