// Generated by gencpp from file template_sm/StringRequest.msg
// DO NOT EDIT!


#ifndef TEMPLATE_SM_MESSAGE_STRINGREQUEST_H
#define TEMPLATE_SM_MESSAGE_STRINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace template_sm
{
template <class ContainerAllocator>
struct StringRequest_
{
  typedef StringRequest_<ContainerAllocator> Type;

  StringRequest_()
    : exampleInput()  {
    }
  StringRequest_(const ContainerAllocator& _alloc)
    : exampleInput(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _exampleInput_type;
  _exampleInput_type exampleInput;




  typedef boost::shared_ptr< ::template_sm::StringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::template_sm::StringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StringRequest_

typedef ::template_sm::StringRequest_<std::allocator<void> > StringRequest;

typedef boost::shared_ptr< ::template_sm::StringRequest > StringRequestPtr;
typedef boost::shared_ptr< ::template_sm::StringRequest const> StringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::template_sm::StringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::template_sm::StringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace template_sm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::template_sm::StringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::template_sm::StringRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::template_sm::StringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::template_sm::StringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::template_sm::StringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::template_sm::StringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::template_sm::StringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e95c171452584b2177d8df6f7324c0ab";
  }

  static const char* value(const ::template_sm::StringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe95c171452584b21ULL;
  static const uint64_t static_value2 = 0x77d8df6f7324c0abULL;
};

template<class ContainerAllocator>
struct DataType< ::template_sm::StringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "template_sm/StringRequest";
  }

  static const char* value(const ::template_sm::StringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::template_sm::StringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string exampleInput\n\
";
  }

  static const char* value(const ::template_sm::StringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::template_sm::StringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.exampleInput);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::template_sm::StringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::template_sm::StringRequest_<ContainerAllocator>& v)
  {
    s << indent << "exampleInput: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.exampleInput);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMPLATE_SM_MESSAGE_STRINGREQUEST_H
